#主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring:
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      # 目录不存在抛异常
      location: d:/test
      max-file-size: 10mb # 注意和proteries大小写
      max-request-size: 15mb

logging:
  config: classpath:logback-demo.xml

---
# dev
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:D:/demo/demo_spring_boot;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
server:
  port: 80

---
# test
spring:
  profiles: test
server:
  port: 8080

---
# prod
spring:
  profiles: prod
server:
  port: 8081