#主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring:
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      # 目录不存在抛异常
      location: d:/test
      max-file-size: 10mb # 注意和proteries大小写
      max-request-size: 15mb

logging:
  config: classpath:logback-demo.xml


#spring.http.multipart.enabled=true
#spring.http.multipart.file-size-threshold=0
#spring.http.multipart.location=d:/tmp
#spring.http.multipart.max-file-size=5Mb 注意大小写
#spring.http.multipart.max-request-size=10Mb
---
# dev
spring:
  profiles: dev
server:
  port: 80


---
# test
spring:
  profiles: test
server:
  port: 8080

---
# prod
spring:
  profiles: prod
server:
  port: 8081