#主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
spring:
  profiles:
    active: dev
logging:
  config: classpath:logback-demo.xml

---
# dev
spring:
  profiles: dev
server:
  port: 80


---
# test
spring:
  profiles: test
server:
  port: 8080

---
# prod
spring:
  profiles: prod
server:
  port: 8081